import type { Track } from '@spot-the-song/shared'

export const SEED_TRACKS: Track[] = [
  {
    id: 'track_billie_jean',
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    album: 'Thriller',
    year: 1982,
    previewUrl: 'https://p.scdn.co/mp3-preview/placeholder-billie',
  },
  {
    id: 'track_smells_like',
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
  },
  {
    id: 'track_rolling_in',
    title: 'Rolling in the Deep',
    artist: 'Adele',
    album: '21',
    year: 2010,
  },
  {
    id: 'track_uptown_funk',
    title: 'Uptown Funk',
    artist: 'Mark Ronson',
    album: 'Uptown Special',
    year: 2014,
  },
  {
    id: 'track_blinding_lights',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    year: 2019,
  },
  {
    id: 'track_hotel_california',
    title: 'Hotel California',
    artist: 'Eagles',
    album: 'Hotel California',
    year: 1976,
  },
  {
    id: 'track_shape_of_you',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    album: '÷ (Divide)',
    year: 2017,
  },
  {
    id: 'track_bohemian',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    year: 1975,
  },
  {
    id: 'track_bad_guy',
    title: 'bad guy',
    artist: 'Billie Eilish',
    album: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
    year: 2019,
  },
  {
    id: 'track_wonderwall',
    title: 'Wonderwall',
    artist: 'Oasis',
    album: "(What's the Story) Morning Glory?",
    year: 1995,
  },
  {
    id: 'track_crazy_in_love',
    title: 'Crazy in Love',
    artist: 'Beyoncé',
    album: 'Dangerously in Love',
    year: 2003,
  },
  {
    id: 'track_purple_rain',
    title: 'Purple Rain',
    artist: 'Prince',
    album: 'Purple Rain',
    year: 1984,
  },
]
